theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
