[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "java"
language-servers = ["jdtls"]
